services:
    PLejeune\TableBundle\Service\TableService:
        public : true
        class: PLejeune\TableBundle\Service\TableService
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    plejeune.table:
        public : true
        alias: PLejeune\TableBundle\Service\TableService
